"""
Markdown report generator for scan2report.
Produces a professional penetration testing report in Markdown format,
covering executive summary, detailed findings, risk assessment, and
prioritised remediation recommendations.
"""

import os
from datetime import datetime


# ── Risk helpers ──────────────────────────────────────────────────────────────

def _overall_risk(analysis: dict) -> str:
    """Derive the overall engagement risk level from the analysis dict."""
    tool = analysis.get("tool", "")

    if tool == "Nmap":
        risky = analysis.get("risky_ports", [])
        # Check NSE vuln scripts
        for host in analysis.get("findings", []):
            for script in host.get("scripts", []):
                if any(k in script.get("output", "").lower()
                       for k in ["vulnerable", "exploit", "cve-"]):
                    return "HIGH"
        if len(risky) >= 3:
            return "HIGH"
        if len(risky) >= 1:
            return "MEDIUM"
        return "LOW"

    if tool == "Nikto":
        if analysis.get("high_count", 0) > 0:
            return "HIGH"
        if analysis.get("medium_count", 0) > 0:
            return "MEDIUM"
        return "LOW"

    if tool == "SQLmap":
        if analysis.get("injections") or analysis.get("dump"):
            return "CRITICAL"
        if analysis.get("databases"):
            return "HIGH"
        return "MEDIUM"

    return "UNKNOWN"


def _risk_badge(level: str) -> str:
    """Return an emoji badge for a risk level string."""
    return {
        "CRITICAL": "🔴 **CRITICAL**",
        "HIGH":     "🔴 **HIGH**",
        "MEDIUM":   "🟡 **MEDIUM**",
        "LOW":      "🟢 **LOW**",
        "INFO":     "🔵 **INFO**",
    }.get(level.upper(), f"⚪ **{level}**")


def _severity_row(label: str, count: int) -> str:
    badge = _risk_badge(label)
    return f"| {badge} | {count} |"


# ── Public API ────────────────────────────────────────────────────────────────

def generate_md_report(
    analysis: dict,
    output_dir: str = ".",
    filename: str = "report.md",
) -> str:
    """
    Generate a professional penetration testing report in Markdown.

    Args:
        analysis:   Analysis dict produced by analyzer.analyze()
        output_dir: Directory to save the file (created if missing)
        filename:   Output filename (default: report.md)

    Returns:
        The full path of the saved .md file.
    """
    os.makedirs(output_dir, exist_ok=True)
    filepath = os.path.join(output_dir, filename)

    sections = _build_report(analysis)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n\n".join(sections))
        f.write("\n")

    return filepath


# ── Report builder ────────────────────────────────────────────────────────────

def _build_report(analysis: dict) -> list[str]:
    """Assemble all report sections in order."""
    tool    = analysis.get("tool", "Unknown")
    risk    = _overall_risk(analysis)
    now     = datetime.now()
    date_str = now.strftime("%B %d, %Y")
    time_str = now.strftime("%H:%M UTC")

    sections = []
    sections.append(_cover(tool, risk, date_str, time_str))
    sections.append(_toc())
    sections.append(_executive_summary(analysis, tool, risk, date_str))
    sections.append(_scope_and_methodology(analysis, tool))
    sections.append(_findings_section(analysis, tool))
    sections.append(_risk_assessment(analysis, tool, risk))
    sections.append(_recommendations(analysis))
    sections.append(_appendix(analysis, tool))
    sections.append(_footer(now))

    return sections


# ── Cover page ────────────────────────────────────────────────────────────────

def _cover(tool: str, risk: str, date_str: str, time_str: str) -> str:
    badge = _risk_badge(risk)
    return f"""\
# Penetration Testing Report

---

| Field | Value |
|---|---|
| **Report Title** | {tool} Security Assessment |
| **Classification** | Confidential |
| **Date** | {date_str} |
| **Time** | {time_str} |
| **Generated By** | scan2report |
| **Overall Risk** | {badge} |

---

> ⚠️ **Confidential:** This document contains sensitive security information.
> Distribution is restricted to authorised personnel only.\
"""


# ── Table of contents ─────────────────────────────────────────────────────────

def _toc() -> str:
    return """\
## Table of Contents

1. [Executive Summary](#executive-summary)
2. [Scope and Methodology](#scope-and-methodology)
3. [Findings](#findings)
4. [Risk Assessment](#risk-assessment)
5. [Recommendations](#recommendations)
6. [Appendix](#appendix)\
"""


# ── Executive summary ─────────────────────────────────────────────────────────

def _executive_summary(analysis: dict, tool: str, risk: str, date_str: str) -> str:
    badge    = _risk_badge(risk)
    overview = analysis.get("overview", "No overview available.")

    # Build metrics table
    metrics = _executive_metrics(analysis, tool, risk)
    metrics_md = "\n".join(f"| {k} | {v} |" for k, v in metrics.items())

    # Write a non-technical narrative
    narrative = _executive_narrative(analysis, tool, risk)

    return f"""\
## Executive Summary

{narrative}

### Key Metrics

| Metric | Value |
|---|---|
{metrics_md}

### Scan Overview

{overview}\
"""


def _executive_metrics(analysis: dict, tool: str, risk: str) -> dict:
    badge = _risk_badge(risk)
    metrics = {"Overall Risk": badge}

    if tool == "Nmap":
        findings = analysis.get("findings", [])
        metrics["Hosts Scanned"]      = len(findings)
        metrics["Hosts Reachable"]    = sum(1 for h in findings if h.get("status") == "up")
        metrics["Total Open Ports"]   = sum(h.get("open_ports", 0) for h in findings)
        metrics["Risky Services"]     = len(analysis.get("risky_ports", []))

    elif tool == "Nikto":
        metrics["Target Host"]        = (
            analysis.get("target", {}).get("hostname")
            or analysis.get("target", {}).get("ip", "—")
        )
        metrics["Total Findings"]     = len(analysis.get("findings", []))
        metrics["High Severity"]      = analysis.get("high_count", 0)
        metrics["Medium Severity"]    = analysis.get("medium_count", 0)
        metrics["Informational"]      = analysis.get("info_count", 0)
        cve_refs = analysis.get("cve_refs", [])
        if cve_refs:
            metrics["CVEs Referenced"] = ", ".join(cve_refs)

    elif tool == "SQLmap":
        target = analysis.get("target", {})
        metrics["Target URL"]         = target.get("url", "—")
        metrics["Database Engine"]    = target.get("dbms", "—")
        metrics["Injectable Params"]  = len(analysis.get("injections", []))
        metrics["Databases Exposed"]  = len(analysis.get("databases", []))
        metrics["Tables Exposed"]     = sum(len(v) for v in analysis.get("tables", {}).values())
        dump = analysis.get("dump", {})
        if dump:
            rows = sum(len(v.get("rows", [])) for v in dump.values())
            metrics["Data Rows Dumped"] = rows
        waf = analysis.get("waf", {})
        metrics["WAF Detected"]       = waf.get("name") or ("Yes" if waf.get("detected") else "No")

    return metrics


def _executive_narrative(analysis: dict, tool: str, risk: str) -> str:
    if tool == "Nmap":
        risky = analysis.get("risky_ports", [])
        hosts_up = sum(1 for h in analysis.get("findings", []) if h.get("status") == "up")
        if risk == "HIGH":
            return (
                f"A network port scan identified **{hosts_up} reachable host(s)** "
                f"with **{len(risky)} high-risk service(s)** exposed to the network. "
                "Several services are either unencrypted, known exploit targets, or databases "
                "with no apparent access controls. Immediate remediation is recommended before "
                "these services can be leveraged as entry points."
            )
        if risk == "MEDIUM":
            return (
                f"A network port scan identified **{hosts_up} reachable host(s)**. "
                "Some services with elevated risk were found. These should be reviewed "
                "and hardened as part of routine security maintenance."
            )
        return (
            f"A network port scan identified **{hosts_up} reachable host(s)**. "
            "No immediately critical services were detected. Continued monitoring is advised."
        )

    if tool == "Nikto":
        high = analysis.get("high_count", 0)
        med  = analysis.get("medium_count", 0)
        if risk in ("HIGH", "CRITICAL"):
            return (
                f"A web server assessment identified **{high} high-severity** and "
                f"**{med} medium-severity** vulnerabilities. "
                "High-severity issues, including potential for cross-site scripting, "
                "information disclosure, or remote code execution, require immediate attention. "
                "The affected server should be patched and hardened before further exposure."
            )
        if risk == "MEDIUM":
            return (
                f"A web server assessment identified **{med} medium-severity** issue(s). "
                "These findings represent meaningful security weaknesses that could be chained "
                "with other vulnerabilities to compromise the target. Remediation is recommended."
            )
        return (
            "A web server assessment was completed. No high or medium severity issues were found. "
            "Informational findings are documented below for completeness."
        )

    if tool == "SQLmap":
        inj = len(analysis.get("injections", []))
        dbs = len(analysis.get("databases", []))
        dump = analysis.get("dump", {})
        rows = sum(len(v.get("rows", [])) for v in dump.values())
        msg = (
            f"A SQL injection assessment identified **{inj} injectable parameter(s)** "
            f"leading to full database access. **{dbs} database(s)** were enumerated"
        )
        if rows:
            msg += f" and **{rows} data row(s)** were successfully extracted"
        msg += (
            ". SQL injection is a critical vulnerability class (OWASP Top 10 A03:2021). "
            "All affected parameters must be remediated using parameterised queries immediately, "
            "and any exposed credentials should be treated as compromised."
        )
        return msg

    return analysis.get("overview", "")


# ── Scope and methodology ─────────────────────────────────────────────────────

def _scope_and_methodology(analysis: dict, tool: str) -> str:
    tool_descriptions = {
        "Nmap": (
            "**Nmap** (Network Mapper) was used to perform active reconnaissance. "
            "The scan enumerated live hosts, open TCP/UDP ports, running services, "
            "service version banners, and operating system fingerprints. "
            "NSE (Nmap Scripting Engine) scripts were executed to detect known vulnerabilities."
        ),
        "Nikto": (
            "**Nikto** was used to perform an automated web server assessment. "
            "The tool sent a series of test requests to identify misconfigurations, "
            "outdated software, dangerous HTTP methods, missing security headers, "
            "exposed files, and known CVEs."
        ),
        "SQLmap": (
            "**SQLmap** was used to detect and exploit SQL injection vulnerabilities. "
            "The tool tested HTTP parameters for various injection techniques including "
            "boolean-based blind, time-based blind, error-based, and UNION-based injections. "
            "Database enumeration and data extraction were performed where possible."
        ),
    }

    desc = tool_descriptions.get(tool, f"**{tool}** was used to perform this assessment.")

    # Extract scan command if Nmap
    cmd_section = ""
    if tool == "Nmap" and analysis.get("scan_command"):
        cmd_section = f"\n\n**Scan Command:**\n```\n{analysis['scan_command']}\n```"

    # Extract target from Nikto / SQLmap
    target_section = ""
    if tool == "Nikto":
        tgt = analysis.get("target", {})
        host = tgt.get("hostname") or tgt.get("ip", "—")
        port = tgt.get("port", "—")
        target_section = f"\n\n**Target:** `{host}:{port}`"
    elif tool == "SQLmap":
        url = analysis.get("target", {}).get("url", "—")
        target_section = f"\n\n**Target URL:** `{url}`"

    return f"""\
## Scope and Methodology

{desc}{cmd_section}{target_section}

### Disclaimer

This report documents findings from automated scanning tools. Results may include
false positives and should be validated by a qualified security professional before
remediation decisions are made. The scope of this assessment is limited to the
targets and techniques described above.\
"""


# ── Findings ──────────────────────────────────────────────────────────────────

def _findings_section(analysis: dict, tool: str) -> str:
    if tool == "Nmap":
        return _nmap_findings(analysis)
    if tool == "Nikto":
        return _nikto_findings(analysis)
    if tool == "SQLmap":
        return _sqlmap_findings(analysis)
    return "## Findings\n\nNo findings available."


def _nmap_findings(analysis: dict) -> str:
    lines = ["## Findings"]
    risky_ports = {(r["host"], r["port"]): r["note"] for r in analysis.get("risky_ports", [])}

    for i, host in enumerate(analysis.get("findings", []), 1):
        address    = host.get("host", "unknown")
        status     = host.get("status", "unknown")
        os_info    = host.get("os") or "Unknown"
        mac        = host.get("mac_address") or "—"
        vendor     = host.get("mac_vendor") or "—"
        open_ports = host.get("ports", [])
        scripts    = host.get("scripts", [])

        # Determine host risk
        host_risky = [p for p in open_ports if (address, p["port"]) in risky_ports]
        host_risk  = "HIGH" if len(host_risky) >= 2 else ("MEDIUM" if host_risky else "LOW")

        lines.append(f"### Finding {i} — Host: `{address}`")
        lines.append(f"**Severity:** {_risk_badge(host_risk)}  ")
        lines.append(f"**Status:** {status}  ")
        lines.append(f"**Operating System:** {os_info}  ")
        lines.append(f"**MAC Address:** `{mac}` ({vendor})  ")
        lines.append(f"**Open Ports:** {len(open_ports)}")
        lines.append("")

        if open_ports:
            lines.append("#### Open Ports")
            lines.append("")
            lines.append("| Port | Protocol | Service | Version | Risk |")
            lines.append("|---|---|---|---|---|")
            for p in open_ports:
                ver  = p.get("version") or "—"
                note = p.get("risk_note")
                risk_cell = f"⚠️ {note}" if note else "✅ Low"
                lines.append(
                    f"| `{p['port']}` | {p['protocol']} | {p['service']} | {ver} | {risk_cell} |"
                )
            lines.append("")

        if scripts:
            lines.append("#### Script Results")
            lines.append("")
            for s in scripts:
                lines.append(f"- **{s['name']}:** {s['output']}")
            lines.append("")

        lines.append("---")

    return "\n".join(lines)


def _nikto_findings(analysis: dict) -> str:
    lines = ["## Findings"]
    findings = analysis.get("findings", [])

    # Group by severity
    for severity in ("HIGH", "MEDIUM", "INFO"):
        group = [f for f in findings if f.get("severity") == severity]
        if not group:
            continue

        lines.append(f"### {_risk_badge(severity)} Findings ({len(group)})")
        lines.append("")

        for i, f in enumerate(group, 1):
            desc     = f.get("description", "")
            url_path = f.get("url_path")
            osvdb    = f.get("osvdb_id")
            cve      = f.get("cve")

            lines.append(f"#### {severity}-{i:02d}: {desc[:80]}")
            lines.append("")
            lines.append(f"**Severity:** {_risk_badge(severity)}  ")
            if url_path:
                lines.append(f"**Affected Path:** `{url_path}`  ")
            if osvdb:
                lines.append(f"**OSVDB Reference:** OSVDB-{osvdb}  ")
            if cve:
                lines.append(f"**CVE:** [{cve}](https://nvd.nist.gov/vuln/detail/{cve})  ")
            lines.append("")
            lines.append(f"> {desc}")
            lines.append("")
            lines.append("---")

    return "\n".join(lines)


def _sqlmap_findings(analysis: dict) -> str:
    lines = ["## Findings"]

    # Injection points
    injections = analysis.get("injections", [])
    if injections:
        lines.append("### Finding 1 — SQL Injection Vulnerability")
        lines.append("")
        lines.append(f"**Severity:** {_risk_badge('CRITICAL')}  ")
        lines.append(f"**Target URL:** `{analysis.get('target', {}).get('url', '—')}`  ")
        lines.append(f"**Database Engine:** {analysis.get('target', {}).get('dbms', '—')}  ")
        waf = analysis.get("waf", {})
        if waf.get("detected"):
            lines.append(f"**WAF/IPS Detected:** {waf.get('name') or 'Yes'}  ")
        lines.append("")
        lines.append(
            "SQL injection was confirmed in the following parameters. "
            "An attacker can use this vulnerability to read, modify, or delete "
            "database content, bypass authentication, and in some cases execute "
            "operating system commands."
        )
        lines.append("")

        for inj in injections:
            lines.append(f"#### Parameter: `{inj['parameter']}` ({inj['method']})")
            lines.append("")
            lines.append("| Attribute | Value |")
            lines.append("|---|---|")
            lines.append(f"| Parameter | `{inj['parameter']}` |")
            lines.append(f"| Method | {inj['method']} |")
            if inj.get("injection_types"):
                lines.append(f"| Injection Types | {', '.join(inj['injection_types'])} |")
            lines.append("")

            if inj.get("payloads"):
                lines.append("**Proof-of-Concept Payloads:**")
                lines.append("")
                lines.append("```")
                for payload in inj["payloads"]:
                    lines.append(payload)
                lines.append("```")
                lines.append("")

        lines.append("---")

    # Database enumeration
    databases = analysis.get("databases", [])
    tables    = analysis.get("tables", {})
    if databases:
        lines.append("### Finding 2 — Database Enumeration")
        lines.append("")
        lines.append(f"**Severity:** {_risk_badge('HIGH')}  ")
        lines.append("")
        lines.append(
            "The following databases and tables were successfully enumerated, "
            "indicating the application database account has excessive privileges."
        )
        lines.append("")
        lines.append("**Databases Found:**")
        lines.append("")
        for db in databases:
            tbl_list = tables.get(db, [])
            if tbl_list:
                lines.append(f"- `{db}` ({len(tbl_list)} table(s): {', '.join(f'`{t}`' for t in tbl_list)})")
            else:
                lines.append(f"- `{db}`")
        lines.append("")
        lines.append("---")

    # Dump data
    dump = analysis.get("dump", {})
    if dump:
        lines.append("### Finding 3 — Data Exfiltration")
        lines.append("")
        lines.append(f"**Severity:** {_risk_badge('CRITICAL')}  ")
        lines.append("")
        lines.append(
            "The following data was successfully extracted from the database. "
            "Any credentials or personal data in this output must be treated as compromised."
        )
        lines.append("")
        for tbl, tbl_data in dump.items():
            cols = tbl_data.get("columns", [])
            rows = tbl_data.get("rows", [])
            lines.append(f"**Table: `{tbl}`** ({len(rows)} row(s))")
            lines.append("")
            if cols and rows:
                header = "| " + " | ".join(f"**{c}**" for c in cols) + " |"
                divider = "| " + " | ".join("---" for _ in cols) + " |"
                lines.append(header)
                lines.append(divider)
                for row in rows:
                    cells = " | ".join(str(row.get(c, "—")) for c in cols)
                    lines.append(f"| {cells} |")
                lines.append("")
        lines.append("---")

    return "\n".join(lines)


# ── Risk assessment ───────────────────────────────────────────────────────────

def _risk_assessment(analysis: dict, tool: str, overall_risk: str) -> str:
    lines = [
        "## Risk Assessment",
        "",
        "### Overall Risk Rating",
        "",
        f"**{_risk_badge(overall_risk)}**",
        "",
        "### Severity Breakdown",
        "",
        "| Severity | Count |",
        "|---|---|",
    ]

    if tool == "Nmap":
        risky = analysis.get("risky_ports", [])
        total_open = sum(h.get("open_ports", 0) for h in analysis.get("findings", []))
        high_ports = [r for r in risky if any(
            p in r["note"].lower()
            for p in ["telnet", "ftp", "smb", "rdp", "vnc", "shell", "rsh"]
        )]
        lines.append(_severity_row("HIGH",   len(high_ports)))
        lines.append(_severity_row("MEDIUM", len(risky) - len(high_ports)))
        lines.append(_severity_row("LOW",    total_open - len(risky)))

    elif tool == "Nikto":
        lines.append(_severity_row("HIGH",   analysis.get("high_count", 0)))
        lines.append(_severity_row("MEDIUM", analysis.get("medium_count", 0)))
        lines.append(_severity_row("INFO",   analysis.get("info_count", 0)))

    elif tool == "SQLmap":
        inj   = len(analysis.get("injections", []))
        dbs   = len(analysis.get("databases", []))
        dump  = analysis.get("dump", {})
        lines.append(_severity_row("CRITICAL", 1 if inj > 0 or dump else 0))
        lines.append(_severity_row("HIGH",     1 if dbs > 0 else 0))
        lines.append(_severity_row("MEDIUM",   1 if analysis.get("waf", {}).get("detected") else 0))

    lines += [
        "",
        "### Risk Rating Definitions",
        "",
        "| Rating | Definition |",
        "|---|---|",
        "| 🔴 **CRITICAL** | Immediate exploitation possible; data breach likely without action |",
        "| 🔴 **HIGH** | Significant vulnerability; exploitation is straightforward |",
        "| 🟡 **MEDIUM** | Vulnerability requires additional steps or conditions to exploit |",
        "| 🟢 **LOW** | Minimal impact; good practice to resolve |",
        "| 🔵 **INFO** | Informational; no direct security impact |",
    ]

    return "\n".join(lines)


# ── Recommendations ───────────────────────────────────────────────────────────

def _recommendations(analysis: dict) -> str:
    recs = analysis.get("recommendations", [])
    lines = [
        "## Recommendations",
        "",
        "The following remediation actions are listed in order of priority.",
        "",
    ]

    for i, rec in enumerate(recs, 1):
        # Strip any inline prefix like [HIGH] or [MEDIUM] for clean display
        import re
        clean = re.sub(r"^\[(HIGH|MEDIUM|LOW|INFO|CRITICAL)\]\s*", "", rec).strip()
        lines.append(f"### {i}. {clean}")
        lines.append("")
        lines.append(_remediation_detail(clean, analysis.get("tool", "")))
        lines.append("")

    if not recs:
        lines.append("No specific remediation actions identified.")

    return "\n".join(lines)


def _remediation_detail(rec: str, tool: str) -> str:
    """Add a short actionable detail paragraph based on the recommendation text."""
    rec_lower = rec.lower()

    if "ftp" in rec_lower:
        return (
            "Disable FTP and replace with SFTP or SCP for secure file transfers. "
            "If FTP is required, enable TLS (FTPS) and restrict access to known IP ranges."
        )
    if "telnet" in rec_lower:
        return (
            "Disable Telnet immediately. Use SSH for all remote administration. "
            "Ensure no default credentials remain on the device."
        )
    if "smb" in rec_lower or "445" in rec_lower:
        return (
            "Disable SMBv1 and apply all relevant security patches (including MS17-010 if applicable). "
            "Restrict SMB access to internal networks only using firewall rules."
        )
    if "rdp" in rec_lower or "3389" in rec_lower:
        return (
            "Restrict RDP access to VPN or jump hosts only. Enable Network Level Authentication (NLA). "
            "Enable account lockout policies to prevent brute-force attacks."
        )
    if "mysql" in rec_lower or "3306" in rec_lower:
        return (
            "Bind the database to localhost (127.0.0.1) and remove external network exposure. "
            "Ensure all database accounts use strong passwords and least-privilege roles."
        )
    if "redis" in rec_lower:
        return (
            "Add authentication to Redis (`requirepass`) and bind to 127.0.0.1 only. "
            "Redis should never be exposed to the internet."
        )
    if "sql injection" in rec_lower or "parameteriz" in rec_lower:
        return (
            "Replace all dynamic SQL string construction with parameterised queries or prepared statements. "
            "Implement an input validation layer and consider a Web Application Firewall (WAF). "
            "Conduct a full code audit to identify all affected query sites."
        )
    if "database" in rec_lower and "expos" in rec_lower:
        return (
            "Review and apply the principle of least privilege to all database accounts. "
            "The web application user should have access only to the tables it needs and "
            "must not have permissions to read system tables or execute administrative commands."
        )
    if "data dump" in rec_lower or "exfiltrat" in rec_lower or "compromised" in rec_lower:
        return (
            "Treat all extracted data as fully compromised. Rotate all exposed credentials immediately. "
            "Notify affected users if personal data was exposed. "
            "Engage your incident response process."
        )
    if "waf" in rec_lower:
        return (
            "Review the WAF ruleset to ensure it blocks all common injection patterns. "
            "WAF bypass is common — defence-in-depth is required. "
            "Fix the underlying vulnerability; do not rely on the WAF alone."
        )
    if "xss" in rec_lower or "cross-site scripting" in rec_lower:
        return (
            "Encode all user-supplied output in the correct context (HTML, JS, URL). "
            "Implement a strict Content-Security-Policy (CSP) header. "
            "Use a template engine with auto-escaping enabled."
        )
    if "x-frame" in rec_lower or "clickjacking" in rec_lower:
        return (
            "Add the `X-Frame-Options: DENY` or `SAMEORIGIN` response header to all pages. "
            "Alternatively, configure a Content-Security-Policy `frame-ancestors` directive."
        )
    if "x-content-type" in rec_lower:
        return "Add the `X-Content-Type-Options: nosniff` header to all HTTP responses."
    if "cookie" in rec_lower or "httponly" in rec_lower:
        return (
            "Set the `HttpOnly` and `Secure` flags on all session cookies. "
            "Use the `SameSite=Strict` or `SameSite=Lax` attribute to prevent CSRF."
        )
    if "phpinfo" in rec_lower or "information disclosure" in rec_lower:
        return (
            "Remove all debugging and informational pages from production environments. "
            "Disable `phpinfo()`, server banners, and error message details."
        )
    if "nse" in rec_lower or "script" in rec_lower:
        return (
            "Review the flagged NSE script output carefully and apply vendor patches for any "
            "identified CVEs. Prioritise patching based on CVSS score."
        )
    # Generic fallback
    return (
        "Investigate and resolve this finding according to your organisation's "
        "vulnerability management policy and risk tolerance."
    )


# ── Appendix ──────────────────────────────────────────────────────────────────

def _appendix(analysis: dict, tool: str) -> str:
    lines = ["## Appendix"]

    if tool == "Nmap":
        lines += _appendix_nmap(analysis)
    elif tool == "Nikto":
        lines += _appendix_nikto(analysis)
    elif tool == "SQLmap":
        lines += _appendix_sqlmap(analysis)

    lines.append("")
    lines.append("### References")
    lines.append("")
    lines.append("- [OWASP Top 10](https://owasp.org/www-project-top-ten/)")
    lines.append("- [NVD CVE Database](https://nvd.nist.gov/)")
    lines.append("- [NIST Vulnerability Scoring (CVSS)](https://www.first.org/cvss/)")
    lines.append("- [CIS Benchmarks](https://www.cisecurity.org/cis-benchmarks/)")

    return "\n".join(lines)


def _appendix_nmap(analysis: dict) -> list:
    lines = ["", "### A. Full Port Table", ""]
    lines.append("| Host | Port | Protocol | State | Service | Version | Risk Note |")
    lines.append("|---|---|---|---|---|---|---|")

    for host in analysis.get("findings", []):
        address = host.get("host", "—")
        for p in host.get("ports", []):
            note = p.get("risk_note") or "—"
            ver  = p.get("version") or "—"
            lines.append(
                f"| `{address}` | `{p['port']}` | {p['protocol']} "
                f"| {p['state']} | {p['service']} | {ver} | {note} |"
            )

    risky = analysis.get("risky_ports", [])
    if risky:
        lines += ["", "### B. Risky Services Summary", ""]
        lines.append("| Host | Port | Risk Description |")
        lines.append("|---|---|---|")
        for r in risky:
            lines.append(f"| `{r['host']}` | `{r['port']}` | {r['note']} |")

    return lines


def _appendix_nikto(analysis: dict) -> list:
    lines = ["", "### A. All Findings", ""]
    lines.append("| Severity | Path | OSVDB | CVE | Description |")
    lines.append("|---|---|---|---|---|")

    for f in analysis.get("findings", []):
        sev   = f.get("severity", "INFO")
        path  = f.get("url_path") or "—"
        osvdb = f"OSVDB-{f['osvdb_id']}" if f.get("osvdb_id") else "—"
        cve   = f.get("cve") or "—"
        desc  = f.get("description", "")[:80]
        lines.append(f"| {sev} | `{path}` | {osvdb} | {cve} | {desc} |")

    return lines


def _appendix_sqlmap(analysis: dict) -> list:
    lines = []

    databases = analysis.get("databases", [])
    tables    = analysis.get("tables", {})
    columns   = analysis.get("columns", {})

    if databases:
        lines += ["", "### A. Database Schema", ""]
        for db in databases:
            tbl_list = tables.get(db, [])
            lines.append(f"**Database:** `{db}`")
            if tbl_list:
                lines.append("")
                lines.append("| Table | Columns |")
                lines.append("|---|---|")
                for tbl in tbl_list:
                    col_list = columns.get(tbl, [])
                    col_str  = ", ".join(f"`{c['name']}` ({c['type']})" for c in col_list) or "—"
                    lines.append(f"| `{tbl}` | {col_str} |")
                lines.append("")

    dump = analysis.get("dump", {})
    if dump:
        lines += ["", "### B. Extracted Data", ""]
        for tbl, tbl_data in dump.items():
            cols = tbl_data.get("columns", [])
            rows = tbl_data.get("rows", [])
            lines.append(f"**Table: `{tbl}`**")
            lines.append("")
            if cols and rows:
                lines.append("| " + " | ".join(cols) + " |")
                lines.append("| " + " | ".join("---" for _ in cols) + " |")
                for row in rows:
                    cells = " | ".join(str(row.get(c, "—")) for c in cols)
                    lines.append(f"| {cells} |")
                lines.append("")

    inj = analysis.get("injections", [])
    if inj:
        lines += ["", "### C. Injection Parameters", ""]
        lines.append("| Parameter | Method | Injection Types |")
        lines.append("|---|---|---|")
        for i in inj:
            types = ", ".join(i.get("injection_types", []))
            lines.append(f"| `{i['parameter']}` | {i['method']} | {types} |")

    return lines


# ── Footer ────────────────────────────────────────────────────────────────────

def _footer(now: datetime) -> str:
    return f"""\
---

*Report generated by **scan2report** on {now.strftime("%B %d, %Y at %H:%M UTC")}.*
*This is an automated report. All findings should be validated by a qualified security professional.*\
"""
