"""
Reporter module.
Generates a plain-text report from analyzed scan data.
"""

import os
from datetime import datetime


def generate_report(analysis: dict, output_dir: str = ".") -> str:
    """
    Write a plain-text report file from analysis data.

    Returns the path of the saved report file.
    """
    tool = analysis.get("tool", "Unknown")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"report_{tool.lower()}_{timestamp}.txt"
    filepath = os.path.join(output_dir, filename)

    lines = _build_report_lines(analysis, tool, timestamp)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return filepath


def _build_report_lines(analysis: dict, tool: str, timestamp: str) -> list:
    """Build the list of lines that make up the report."""
    lines = []

    lines += _header(tool, timestamp)
    lines += _section("OVERVIEW", [analysis.get("overview", "No overview available.")])

    if tool == "Nmap":
        lines += _nmap_section(analysis)
    elif tool == "Nikto":
        lines += _nikto_section(analysis)
    elif tool == "SQLmap":
        lines += _sqlmap_section(analysis)

    lines += _section("RECOMMENDATIONS", analysis.get("recommendations", ["None."]))
    lines += _footer()

    return lines


def _header(tool: str, timestamp: str) -> list:
    width = 60
    lines = [
        "=" * width,
        f"  SCAN2REPORT — {tool.upper()} SCAN REPORT",
        f"  Generated: {timestamp.replace('_', ' ')}",
        "=" * width,
        "",
    ]
    return lines


def _footer() -> list:
    return [
        "",
        "=" * 60,
        "  End of Report — Generated by scan2report",
        "=" * 60,
    ]


def _section(title: str, items: list) -> list:
    lines = [
        "",
        f"{'─' * 60}",
        f"  {title}",
        f"{'─' * 60}",
    ]
    for item in items:
        lines.append(f"  {item}")
    return lines


def _nmap_section(analysis: dict) -> list:
    lines = []
    findings = analysis.get("findings", [])

    lines += [
        "",
        "─" * 60,
        "  HOST DETAILS",
        "─" * 60,
    ]

    for host_data in findings:
        lines.append(f"")
        lines.append(f"  Host      : {host_data.get('host', 'unknown')}")
        lines.append(f"  Status    : {host_data.get('status', 'unknown')}")
        if host_data.get("os"):
            lines.append(f"  OS        : {host_data['os']}")
        open_ports = host_data.get("ports", [])
        lines.append(f"  Open Ports: {len(open_ports)}")
        for port in open_ports:
            version = f" — {port['version']}" if port.get("version") else ""
            lines.append(
                f"    {port['port']}/{port['protocol']}  {port['service']}{version}"
            )

    return lines


def _nikto_section(analysis: dict) -> list:
    lines = []

    target = analysis.get("target", {})
    if target:
        lines += [
            "",
            "─" * 60,
            "  TARGET INFO",
            "─" * 60,
            f"  Host    : {target.get('hostname') or target.get('ip', 'unknown')}",
            f"  Port    : {target.get('port', 'unknown')}",
            f"  Server  : {target.get('server', 'unknown')}",
        ]

    findings = analysis.get("findings", [])
    if findings:
        lines += [
            "",
            "─" * 60,
            "  FINDINGS",
            "─" * 60,
        ]
        for f in findings:
            lines.append(f"  [{f['severity']:6}] {f['description']}")

    return lines


def _sqlmap_section(analysis: dict) -> list:
    lines = []

    target = analysis.get("target", {})
    if target:
        lines += [
            "",
            "─" * 60,
            "  TARGET INFO",
            "─" * 60,
            f"  URL     : {target.get('url', 'unknown')}",
            f"  DBMS    : {target.get('dbms', 'unknown')}",
            f"  OS      : {target.get('web_os', 'unknown')}",
            f"  Tech    : {target.get('web_tech', 'unknown')}",
        ]

    injections = analysis.get("injections", [])
    if injections:
        lines += [
            "",
            "─" * 60,
            "  INJECTION POINTS",
            "─" * 60,
        ]
        for inj in injections:
            lines.append(f"  Parameter : {inj['parameter']} ({inj['method']})")
            for t in inj.get("injection_types", []):
                lines.append(f"    Type    : {t}")
            for p in inj.get("payloads", []):
                lines.append(f"    Payload : {p}")

    databases = analysis.get("databases", [])
    if databases:
        lines += [
            "",
            "─" * 60,
            "  DATABASES FOUND",
            "─" * 60,
        ]
        for db in databases:
            lines.append(f"  - {db}")

    tables = analysis.get("tables", {})
    if tables:
        lines += [
            "",
            "─" * 60,
            "  TABLES FOUND",
            "─" * 60,
        ]
        for db, tbl_list in tables.items():
            lines.append(f"  Database: {db}")
            for tbl in tbl_list:
                lines.append(f"    - {tbl}")

    return lines
